import './globals.css'
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'

const montserrat = Montserrat({ weight: ['400'], subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: {
	children: React.ReactNode
}) {
	return (
		<ClerkProvider>
			<html lang="en">
				<body className={montserrat.className}>
					<div className="mx-10 mt-4">{children}</div>
				</body>
			</html>
		</ClerkProvider>
	)
}
